version: "3.9"
services:
  postgresql:
    image: docker.io/library/postgres:18-alpine
    container_name: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - postgresql_16_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASS:?database password required}
      - POSTGRES_USER=${PG_USER:-root}
    networks:
      - internal

volumes:
  postgresql_16_data:

networks:
  internal:
    name: internal
    external: true
