version: "3.9"
services:  
  pyload:
    image:     image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    restart: always
    volumes: 
      - /nfs/docker/pyload:/config
      - /nfs/downloads:/downloads
    networks:
      - internal
volumes:
  redis:

networks:
  internal:
    name: internal
    external: true
