version: "3.9"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.10.0-ls150
    container_name: code-server
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europ/Berlin
      SUDO_PASSWORD: ${SUDO_PW:-}
      PROXY_DOMAIN: ${PROXY_DOMAIN:-} #optional
      DEFAULT_WORKSPACE: /config/workspace #optional
      DOCKER_MODS: linuxserver/mods:code-server-zsh|linuxserver/mods:code-server-shellcheck|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-npmglobal|linuxserver/mods:code-server-terraform|linuxserver/mods:universal-docker-in-docker
    volumes:
      - config:/config
    networks:
      - internal
    restart: always

volumes:
  config:

networks:
  internal:
    name: internal
    external: true