version: "3.9"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - data:/config
    networks:
      - internal
volumes:
  data:
networks:
  internal:
    name: internal
    external: true
