version: "3.9"

services:
  windmill_server:
    image: ghcr.io/windmill-labs/windmill:main
    name: windmill_server
    pull_policy: always
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${PG_USER:-windmill}:${PG_PASS:?PG_PASS required}@${PG_HOST:-postgres}/${PG_DB:-windmill}?sslmode=disable
      MODE: server

  windmill_worker:
    image: ghcr.io/windmill-labs/windmill:main
    name: windmill_worker
    pull_policy: always
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${PG_USER:-windmill}:${PG_PASS:?PG_PASS required}@${PG_HOST:-postgres}/${PG_DB:-windmill}?sslmode=disable
      MODE: worker
      WORKER_GROUP: default
    # to mount the worker folder to debug, KEEP_JOB_DIR=true and mount /tmp/windmill
    volumes:
      # mount the docker socket to allow to run docker containers from within the workers
      - /var/run/docker.sock:/var/run/docker.sock
      - worker_dependency_cache:/tmp/windmill/cache

  ## This worker is specialized for "native" jobs. Native jobs run in-process and thus are much more lightweight than other jobs
  windmill_worker_native:
    image: ghcr.io/windmill-labs/windmill:main
    name: windmill_worker_native
    pull_policy: always
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${PG_USER:-windmill}:${PG_PASS:?PG_PASS required}@${PG_HOST:-postgres}/${PG_DB:-windmill}?sslmode=disable
      MODE: worker
      WORKER_GROUP: native

  lsp:
    image: ghcr.io/windmill-labs/windmill-lsp:latest
    name: windmill_lsp
    pull_policy: always
    restart: unless-stopped
    volumes:
      - lsp_cache:/root/.cache

  ## This worker is specialized for reports or scraping jobs. It is assigned the "reports" worker group which has an init script that installs chromium and can be targeted by using the "chromium" worker tag.
  # windmill_worker_reports:
  #   image: ghcr.io/windmill-labs/windmill:main
  #   pull_policy: always
  #   restart: unless-stopped
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - MODE=worker
  #     - WORKER_GROUP=reports
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   # to mount the worker folder to debug, KEEP_JOB_DIR=true and mount /tmp/windmill
  #   volumes:
  #     # mount the docker socket to allow to run docker containers from within the workers
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - worker_dependency_cache:/tmp/windmill/cache

volumes:
  worker_dependency_cache: 
  lsp_cache: 
