version: "3.9"
services:
  bookstack:
    image: linuxserver/bookstack:23.02.20230226
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=${DB_HOST:-mariadb}
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${DB_PASS:?database password required}
      - DB_DATABASE=bookstack
      - APP_URL=${APP_URL:-}
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_SERVERS=${REDIS_SERVERS:-redis:6379:0}
      - AUTH_METHOD=oidc
      - AUTH_AUTO_INITIATE=true
      - OIDC_NAME=SSO
      - OIDC_DISPLAY_NAME_CLAIMS=email
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_ISSUER=${OIDC_ISSUER}
      - OIDC_ISSUER_DISCOVER=true
    volumes:
      - data:/config
    restart: always
    networks:
      - internal

networks:
  internal:
    name: internal
    external: true

volumes:
  data: