version: "3.9"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=bookstack
      # Set DB_PASS in portainer
      #- DB_PASS=<yourdbpass>
      - DB_DATABASE=bookstack
    volumes:
      - data:/config
    restart: always
    networks:
      - internal

networks:
  internal:
    name: internal
    external: true

volumes:
  data: