version: "3.9"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=${DB_HOST:-mariadb}
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${DB_PASS:?database password required}
      - DB_DATABASE=bookstack
      - APP_URL=${APP_URL:-}
    volumes:
      - data:/config
    restart: always
    networks:
      - internal

networks:
  internal:
    name: internal
    external: true

volumes:
  data: