version: "3.9"
services:
  plugsy:
    image: plugsy/core:latest
    container_name: plugsy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - internal

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - uptime-kuma-data:/app/data
    restart: always
    # environment:
      # PUID: 1000
      # PGID: 1000
    networks:
      - internal

volumes:
  uptime-kuma-data:

networks:
  internal:
    name: internal
    external: true