version: "3.9"
services:
  plugsy:
    image: plugsy/core:latest
    container_name: plugsy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - internal

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - uptime-kuma-data:/app/data
    restart: always
    # environment:
      # PUID: 1000
      # PGID: 1000
    networks:
      - internal

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - internal
    volumes:
      - /srv/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations, see alternative methods
    environment:
      PUID: $PUID
      PGID: $PGID

  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    restart: unless-stopped
    privileged: true
    networks:
      - internal
    volumes:
      - /:/mnt/host:ro
    environment:
     DASHDOT_ENABLE_CPU_TEMPS: true

volumes:
  uptime-kuma-data:
  homepage:

networks:
  internal:
    name: internal
    external: true