version: "3.9"
services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: always
    networks:
      - internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /nfs/docker/paperless/data:/usr/src/paperless/data
      - /nfs/docker/paperless/media:/usr/src/paperless/media
      - /nfs/docker/paperless/export:/usr/src/paperless/export
      - /nfs/docker/paperless/consume:/usr/src/paperless/consume
    environment:
      USERMAP_UID: 0
      USERMAP_GID: 0
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_CSRF_TRUSTED_ORIGINS: ${CSRF_ALLOWED_HOSTS:? URL is required}
      PAPERLESS_ALLOWED_HOSTS: ${ALLOWED_HOSTS:? URL is required}
      PAPERLESS_CORS_ALLOWED_HOSTS: ${CORS_ALLOWED_HOSTS:? URL is required}
      PAPERLESS_REDIS: ${REDIS:-redis://redis:6379}
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: ${DB_HOST:-mariadb}
      PAPERLESS_DBUSER: ${DB_USER:-paperless}
      PAPERLESS_DBPASS: ${DB_PASS:? Password is required} # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      PAPERLESS_SECRET_KEY: ${SECRET_KEY:? Secret KEy Reuqired} # used for token encryption
      PAPERLESS_OCR_LANGUAGE: deu
      # Admin User & Proxy Login
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: true
      PAPERLESS_LOGOUT_REDIRECT_URL: ${LOGOUT_URL:-None}
      PAPERLESS_ADMIN_USER: ${ADMIN_USER:?- Admin user must be set}
      PAPERLESS_ADMIN_PASSWORD: ${ADMIN_PASS:? Admin Pass must be set}
      # Paperless cusotmizing settings
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"

networks:
  internal:
    name: internal
    external: true