version: "3.9"
services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: always
    networks:
      - internal
    logging:
      driver: journald
      options:
        tag: paperless
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /nfs/docker/paperless/data:/usr/src/paperless/data
      - /nfs/docker/paperless/media:/usr/src/paperless/media
      - /nfs/docker/paperless/export:/usr/src/paperless/export
      - /nfs/docker/paperless/consume:/usr/src/paperless/consume
    environment:
      USERMAP_UID: 0
      USERMAP_GID: 0
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_CSRF_TRUSTED_ORIGINS: ${CSRF_ALLOWED_HOSTS:? URL is required}
      PAPERLESS_ALLOWED_HOSTS: ${ALLOWED_HOSTS:? URL is required}
      PAPERLESS_CORS_ALLOWED_HOSTS: ${CORS_ALLOWED_HOSTS:? URL is required}
      PAPERLESS_REDIS: ${REDIS:-redis://redis:6379}
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: ${DB_HOST:-mariadb}
      PAPERLESS_DBUSER: ${DB_USER:-paperless}
      PAPERLESS_DBPASS: ${DB_PASS:? Password is required} # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      PAPERLESS_SECRET_KEY: ${SECRET_KEY:? Secret KEy Reuqired} # used for token encryption
      PAPERLESS_OCR_LANGUAGE: deu
      # Admin User & OIDC Login
      # PAPERLESS_ENABLE_HTTP_REMOTE_USER: true
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
          "openid_connect": {
            "APPS": [
              {
                "provider_id": "authentik",
                "name": "SSO",
                "client_id": "${OIDC_CLIENT_ID:? Client ID required}",
                "secret": "${OIDC_CLIENT_SECRET:? Client Secret required}",
                "settings": {
                  "server_url": "https://sso.trockel.family/application/o/paperless/.well-known/openid-configuration"
                }
              }
            ],
            "OAUTH_PKCE_ENABLED": "True"
          }
        }

      PAPERLESS_LOGOUT_REDIRECT_URL: ${LOGOUT_URL:-None}
      PAPERLESS_ADMIN_USER: ${ADMIN_USER:? Admin user must be set}
      PAPERLESS_ADMIN_PASSWORD: ${ADMIN_PASS:? Admin Pass must be set}
      # Paperless cusotmizing settings
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"
      # Setup barcode support
      PAPERLESS_CONSUMER_ENABLE_BARCODES: true
      PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: true # enable setting ASN by ASN barcodes
      PAPERLESS_CONSUMER_BARCODE_SCANNER: ZXING # switch from pyzbar to zxing for better recognition

networks:
  internal:
    name: internal
    external: true