version: '3.7'
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.28.0
    container_name: audiobookshelf
    networks:
      - internal
    volumes:
      - config:/config
      - metadata:/metadata
      - /nfs/books/audiobooks:/audiobooks
      - /nfs/books/podcasts:/podcasts
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Europe/Berlin
    restart: unless-stopped
networks:
  internal:
    name: internal
    external: true
volumes:
  config:
  metadata:
