version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: pgadmin
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:? Default Email is required}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:? Default Password is required}
        PGADMIN_LISTEN_PORT: 80
        PGADMIN_DISABLE_POSTFIX: true
    volumes:
        - data:/var/lib/pgadmin
    networks:
      - internal
    healthcheck:
      test: ["CMD", "nc", "-z", "-v", "localhost", "80"]
      interval: 10s
      timeout: 3s

volumes:
  data:
networks:
  internal:
    name: internal
    external: true