---
version: "3.9"
services:
  calibre-web:
    image: linuxserver/calibre-web:0.6.19-ls196
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      #- OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - config:/config
      - /nfs/books:/books
    restart: always
    networks:
      - internal
    healthcheck:
      test: curl -f http://localhost:8083/ || exit 1
      interval: 10s
      timeout: 3s
volumes:
  config:
networks:
  internal:
    name: internal
    external: true
