version: "3.9"
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: always
    volumes:
      - data:/opt/adguardhome/work
      - config:/opt/adguardhome/conf
    networks:
      internal:
      home:
        ipv4_address: ${HOME_IPV4:? IP is required}
    ports:
      - ${HOME_IPV4:? IP is required}:53:53/tcp
      - ${HOME_IPV4:? IP is required}:53:53/udp
  
volumes:
  data:
  config:
networks:
  internal:
    name: internal
    external: true
  home:
    name: home
    external: true