version: '3.5'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    networks:
      - internal
    volumes:
      - /nfs/downloads/tube:/youtube
      - cache:/cache
    environment:
      ES_URL: http://archivist-es:9200
      REDIS_HOST: archivist-redis
      HOST_UID: 1000
      HOST_GID: 1000
      TA_HOST: "${TA_HOST?Variable required}"
      TA_USERNAME: ${TA_USERNAME-admin}
      TA_PASSWORD: ${TA_PASSWORD?Variable required}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD?Variable required}
      TZ: Europe/Berlin
      TA_ENABLE_AUTH_PROXY: ${ENABLE_PROXY-false}
      TA_AUTH_PROXY_USERNAME_HEADER: ${TA_AUTH_PROXY_USERNAME_HEADER-HTTP_REMOTE_USER}
      DJANGO_DEBUG: ${DEBUG-false}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - archivist-redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es  # only for amd64, or use official es 8.13.2
    container_name: archivist-es
    restart: unless-stopped
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD?Variable required}      # matching Elasticsearch password
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: true
      discovery.type: single-node
      path.repo: /usr/share/elasticsearch/data/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    networks:
      - internal

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    networks:
      - internal
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - type: bind
        source: /nfs/video
        target: /media
      - type: bind
        source: /nfs/downloads
        target: /media2
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://stream.local.trockel.family

volumes:
  cache:
  es:
  archivist-redis:
  jellyfin-config:
  jellyfin-cache:

networks:
  internal:
    name: internal
    external: true