version: '3.9'

services:
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DESIGN=pepa-linha
    networks:
      - internal
networks:
  internal:
    name: internal
    external: true