version: "3.9"
services:
  api:
    image: vikunja/api:0.21
    container_name: vikunja_api
    environment:
      VIKUNJA_DATABASE_HOST: mariadb
      VIKUNJA_DATABASE_PASSWORD: ${DB_PASSWORD:? PW is required}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${JWT_SECRET:? Secret is required}
      VIKUNJA_SERVICE_FRONTENDURL: ${FRONTEND_URL:? FRONTEND Url required}
      VIKUNJA_CACHE_ENABLED: ${REDIS_ENABLED:-false}
      VIKUNJA_CACHE_TYPE: redis
      VIKUNJA_REDIS_ENABLED: ${REDIS_ENABLED:-false}
      VIKUNJA_REDIS_HOST: ${REDIS_HOST:-redis:6379}
      VIKUNJA_REDIS_DB: ${REDIS_DB:-0}
      VIKUNJA_SERVICE_ENABLETOTP: false # We use Oauth with 2FA enabled
    volumes: 
      - /nfs/docker/vikunja/files:/app/vikunja/files
      - /nfs/docker/vikunja/config:/etc/vikunja
    networks:
      - internal
    restart: always
  frontend:
    image: vikunja/frontend:0.20
    container_name: vikunja
    networks:
      - internal
    restart: always

networks:
  internal:
    name: internal
    external: true