version: "3.9"
services:
  firefly:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: always
    volumes:
      - upload:/var/www/html/storage/upload
    environment:
      TZ: Europe/Berlin
      APP_KEY : ${APP_KEY:? App Key is required}  
      DB_HOST : ${DB_HOST:-mariadb}  
      DB_PORT : 3306  
      DB_CONNECTION : mysql  
      DB_DATABASE : ${DB_NAME:-firefly}  
      DB_USERNAME : ${DB_USER:-firefly}
      DB_PASSWORD : ${DB_PASS:? Password is required}
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_DB: ${REDIS_DB:-5}
      REDIS_CACHE_DB: ${REDIS_CACHE_DB:-6}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN:? Domain is required}
      COOKE_SECURE: true
      AUTHENTICATION_GUARD: remote_user_guard
      AUTHENTICATION_GUARD_HEADER: X-authentik-username
      AUTHENTICATION_GUARD_EMAIL: X-authentik-email
      APP_URL: ${APP_URL:? APP Url is required}
      TRUSTED_PROXIES: "**"
    networks:
      - internal
  fidi:
    image: fireflyiii/data-importer:latest
    container_name: fidi
    restart: always
    environment:
      TZ: Europe/Berlin
      FIREFLY_III_URL: http://firefly:8080
      VANITY_URL: ${APP_URL:? APP Url is required}
      # FIREFLY_III_ACCESS_TOKEN: ${PAT:? PAT required}
      TRUSTED_PROXIES: "**"
    networks:
      - internal

volumes:
  upload:

networks:
  internal:
    name: internal
    external: true