version: "3.9"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:10.6.10
    container_name: mariadb
    pull_policy: always
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=$ROOT_PASSWORD
      - TZ=Europe/Berlin
    volumes:
      - mariadb_data:/config
    restart: always
    networks:
      - internal

volumes:
  mariadb_data:

networks:
  internal:
    name: internal
    external: true