version: "3.9"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:10.11.8
    container_name: mariadb
    pull_policy: always
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=$ROOT_PASSWORD
      - TZ=Europe/Berlin
    volumes:
      - mariadb_data:/config
    restart: always
    networks:
      - internal
  adminer:
    image: adminer:4.17.1
    container_name: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DESIGN=pepa-linha
    networks:
      - internal
volumes:
  mariadb_data:

networks:
  internal:
    name: internal
    external: true
