---
version: "3.9"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - config:/config
    networks:
      - internal
    restart: always
    
volumes:
  config:
networks:
  internal:
    name: internal
    external: true
