version: "3.9"
services:
  ddclient:
    image: favonia/cloudflare-ddns:1.15.1
    container_name: cloudflare-ddns
    restart: always
    networks:
      - internal
    user: "1000:1000"
    logging:
      driver: journald
      options:
        tag: ddns
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Berlin
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?Variable not set}
      DOMAINS: ${DOMAINS:?Variable not set}
      PROXIED: false
      UPTIMEKUMA: ${UPTIMEKUMA}
      UPDATE_CRON: ${UPDATE_CRON:-@every 5m}
      IP6_PROVIDER: none
      


networks:
  internal:
    name: internal
    external: true
