version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - /nfs/downloads/metube:/downloads
    networks:
      - internal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin

networks:
  internal:
    name: internal
    external: true