version: "3.9"
services: 
  nocodb: 
    image: nocodb/nocodb:latest
    container_name: nocodb
    environment: 
      NC_DB: mysql2://${DB_HOST:-mariadb}:${DB_PORT:-3306}?u=${DB_USER:-noco}&p=${DB_PASS:?Password required}&d=${DB_NAME:-noco}
    restart: always
    volumes: 
      - nc_data:/usr/app/data
    pull_policy: always
    restart: always
    networks:
      - internal

volumes:
  nc_data:

networks:
  internal:
    name: internal
    external: true
    
