services:
  scratchmap:
    image: ad3m3r5/scratch-map:latest
    restart: always
    container_name: scratch-map 
    environment:
      PORT: 8080
      DBLOCATION: /data
    volumes:
      - data:/data
    networks:
      - internal

volumes:
  data:
networks:
  internal:
    name: internal
    external: true